server:
  port: 5230
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: spring-cloud-gateway-application
  cloud:
    consul:
      discovery:
        instance-id: gateway-service-id
        serviceName: gateway-application
        healthCheckPath: /health
