server:
  port: 5231
spring:
  application:
    name: spring-cloud-consul-application
  cloud:
    consul:
      discovery:
        instance-id: consul-service-id
        serviceName: consul-application
        healthCheckPath: /health

logging:
  level:
    root: DEBUG